CREATE TABLE meaning
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    meaning_kr VARCHAR(255)                            NOT NULL,
    meaning_en VARCHAR(255),
    word_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_meaning PRIMARY KEY (id)
);

ALTER TABLE member
    ADD language_preference VARCHAR(5);

UPDATE member SET language_preference = 'KR' WHERE language_preference IS NULL;

ALTER TABLE member
    ALTER COLUMN language_preference SET NOT NULL;

ALTER TABLE meaning
    ADD CONSTRAINT FK_MEANING_ON_WORD FOREIGN KEY (word_id) REFERENCES word (id);

ALTER TABLE word
    DROP COLUMN meaning;

ALTER TABLE word
    DROP COLUMN meaning_en;