CREATE TABLE tag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE word_tag
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word_id BIGINT                                  NOT NULL,
    tag_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_wordtag PRIMARY KEY (id)
);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_name UNIQUE (name);

ALTER TABLE word_tag
    ADD CONSTRAINT FK_WORDTAG_ON_TAG FOREIGN KEY (tag_id) REFERENCES tag (id);

ALTER TABLE word_tag
    ADD CONSTRAINT FK_WORDTAG_ON_WORD FOREIGN KEY (word_id) REFERENCES word (id);