CREATE TABLE inquiry
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT,
    title      VARCHAR(255),
    content    OID,
    status     VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_inquiry PRIMARY KEY (id)
);

CREATE TABLE inquiry_attachment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inquiry_id         BIGINT,
    storage_key        VARCHAR(255),
    original_file_name VARCHAR(255),
    file_size          BIGINT                                  NOT NULL,
    content_type       VARCHAR(255),
    CONSTRAINT pk_inquiryattachment PRIMARY KEY (id)
);

ALTER TABLE inquiry_attachment
    ADD CONSTRAINT FK_INQUIRYATTACHMENT_ON_INQUIRY FOREIGN KEY (inquiry_id) REFERENCES inquiry (id);