CREATE TABLE notification
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient_id BIGINT                                  NOT NULL,
    content      VARCHAR(255)                            NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    is_read      BOOLEAN                                 NOT NULL,
    related_url  VARCHAR(255),
    CONSTRAINT pk_notification PRIMARY KEY (id)
);