CREATE TABLE login_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    login_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_login_history PRIMARY KEY (id)
);