CREATE TABLE blueprint_detail
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_blueprint_id BIGINT,
    category_id       BIGINT,
    question_count    INTEGER                                 NOT NULL,
    sequence          INTEGER                                 NOT NULL,
    CONSTRAINT pk_blueprintdetail PRIMARY KEY (id)
);

CREATE TABLE exam_blueprint
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255),
    description        VARCHAR(255),
    level_id           BIGINT,
    total_time_minutes INTEGER                                 NOT NULL,
    CONSTRAINT pk_examblueprint PRIMARY KEY (id)
);

ALTER TABLE blueprint_detail
    ADD CONSTRAINT FK_BLUEPRINTDETAIL_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES question_category (id);

ALTER TABLE blueprint_detail
    ADD CONSTRAINT FK_BLUEPRINTDETAIL_ON_EXAM_BLUEPRINT FOREIGN KEY (exam_blueprint_id) REFERENCES exam_blueprint (id);

ALTER TABLE exam_blueprint
    ADD CONSTRAINT FK_EXAMBLUEPRINT_ON_LEVEL FOREIGN KEY (level_id) REFERENCES level (id);