ALTER TABLE member_kanji_progress
    ADD COLUMN stability DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
ADD COLUMN difficulty DOUBLE PRECISION DEFAULT 0.0 NOT NULL;

ALTER TABLE member_word_progress
    ADD COLUMN stability DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
ADD COLUMN difficulty DOUBLE PRECISION DEFAULT 0.0 NOT NULL;

ALTER TABLE member
    ALTER COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));