CREATE TABLE filter_log
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id       BIGINT                                  NOT NULL,
    reason_type   VARCHAR(255)                            NOT NULL,
    result_status VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_filterlog PRIMARY KEY (id)
);