CREATE TABLE member
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    auth_type   VARCHAR(31)                             NOT NULL,
    email       VARCHAR(255),
    username    VARCHAR(255),
    role        VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    password    VARCHAR(255),
    provider    VARCHAR(255),
    provider_id VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (id)
);

ALTER TABLE member
    ADD CONSTRAINT uc_member_email UNIQUE (email);