CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    content    TEXT                                    NOT NULL,
    post_id    BIGINT                                  NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE image
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    unique_file_name VARCHAR(255)                            NOT NULL,
    image_url        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE kanji
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character    VARCHAR(10)                             NOT NULL,
    meaning      VARCHAR(255)                            NOT NULL,
    meaning_en   VARCHAR(255),
    onyomi       VARCHAR(255)                            NOT NULL,
    kunyomi      VARCHAR(255)                            NOT NULL,
    stroke_count INTEGER                                 NOT NULL,
    radical      VARCHAR(255),
    jlpt_level   INTEGER,
    CONSTRAINT pk_kanji PRIMARY KEY (id)
);

CREATE TABLE member
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    auth_type   VARCHAR(31)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    email       VARCHAR(255),
    username    VARCHAR(255),
    role        VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255),
    provider    VARCHAR(255),
    provider_id VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (id)
);

CREATE TABLE member_kanji_progress
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id        BIGINT                                  NOT NULL,
    kanji_id         BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    last_reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    next_review_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_member_kanji_progress PRIMARY KEY (id)
);

CREATE TABLE member_word_progress
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id        BIGINT                                  NOT NULL,
    word_id          BIGINT                                  NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    last_reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    next_review_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_member_word_progress PRIMARY KEY (id)
);

CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    title      VARCHAR(100)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    member_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE review_interval
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    review_level  INTEGER                                 NOT NULL,
    interval_days INTEGER                                 NOT NULL,
    CONSTRAINT pk_reviewinterval PRIMARY KEY (id)
);

CREATE TABLE word
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    term       VARCHAR(255)                            NOT NULL,
    reading    VARCHAR(255)                            NOT NULL,
    meaning    VARCHAR(255)                            NOT NULL,
    meaning_en VARCHAR(255),
    CONSTRAINT pk_word PRIMARY KEY (id)
);

CREATE TABLE word_kanjis
(
    kanjis_id BIGINT NOT NULL,
    words_id  BIGINT NOT NULL
);

ALTER TABLE member_kanji_progress
    ADD CONSTRAINT member_kanji_unique UNIQUE (member_id, kanji_id);

ALTER TABLE image
    ADD CONSTRAINT uc_image_uniquefilename UNIQUE (unique_file_name);

ALTER TABLE kanji
    ADD CONSTRAINT uc_kanji_character UNIQUE (character);

ALTER TABLE member
    ADD CONSTRAINT uc_member_email UNIQUE (email);

ALTER TABLE review_interval
    ADD CONSTRAINT uc_reviewinterval_reviewlevel UNIQUE (review_level);

ALTER TABLE member_word_progress
    ADD CONSTRAINT uk_member_word UNIQUE (member_id, word_id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE comment
    ADD CONSTRAINT FK_COMMENT_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE member_kanji_progress
    ADD CONSTRAINT FK_MEMBER_KANJI_PROGRESS_ON_KANJI FOREIGN KEY (kanji_id) REFERENCES kanji (id);

ALTER TABLE member_kanji_progress
    ADD CONSTRAINT FK_MEMBER_KANJI_PROGRESS_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE member_word_progress
    ADD CONSTRAINT FK_MEMBER_WORD_PROGRESS_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE member_word_progress
    ADD CONSTRAINT FK_MEMBER_WORD_PROGRESS_ON_WORD FOREIGN KEY (word_id) REFERENCES word (id);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE word_kanjis
    ADD CONSTRAINT fk_workan_on_kanji FOREIGN KEY (kanjis_id) REFERENCES kanji (id);

ALTER TABLE word_kanjis
    ADD CONSTRAINT fk_workan_on_word FOREIGN KEY (words_id) REFERENCES word (id);