CREATE TABLE image
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    unique_file_name VARCHAR(255)                            NOT NULL,
    image_url        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_image PRIMARY KEY (id)
);

ALTER TABLE image
    ADD CONSTRAINT uc_image_uniquefilename UNIQUE (unique_file_name);

ALTER TABLE member
    ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE member
    ALTER COLUMN provider DROP NOT NULL;

ALTER TABLE member
    ALTER COLUMN provider_id DROP NOT NULL;

ALTER TABLE member
    ALTER COLUMN updated_at DROP NOT NULL;