CREATE TABLE choice
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_id BIGINT,
    choice_text VARCHAR(255),
    is_correct  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_choice PRIMARY KEY (id)
);

CREATE TABLE exam
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level_id           BIGINT,
    title              VARCHAR(255),
    total_time_minutes INTEGER                                 NOT NULL,
    CONSTRAINT pk_exam PRIMARY KEY (id)
);

CREATE TABLE exam_question
(
    exam_id         BIGINT  NOT NULL,
    question_id     BIGINT  NOT NULL,
    question_number INTEGER NOT NULL,
    CONSTRAINT pk_examquestion PRIMARY KEY (exam_id, question_id)
);

CREATE TABLE level
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_level PRIMARY KEY (id)
);

CREATE TABLE member_answer
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    attempt_id         BIGINT,
    question_id        BIGINT,
    selected_choice_id BIGINT,
    is_correct         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_memberanswer PRIMARY KEY (id)
);

CREATE TABLE question
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level_id      BIGINT,
    category_id   BIGINT,
    question_text TEXT,
    passage       TEXT,
    audio_url     VARCHAR(255),
    explanation   TEXT,
    isaigenerated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_question PRIMARY KEY (id)
);

CREATE TABLE question_category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    section_id BIGINT,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_questioncategory PRIMARY KEY (id)
);

CREATE TABLE section
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_section PRIMARY KEY (id)
);

CREATE TABLE test_attempt
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id  BIGINT,
    exam_id    BIGINT,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time   TIMESTAMP WITHOUT TIME ZONE,
    score      INTEGER,
    status     VARCHAR(255),
    CONSTRAINT pk_testattempt PRIMARY KEY (id)
);

ALTER TABLE level
    ADD CONSTRAINT uc_level_name UNIQUE (name);

ALTER TABLE section
    ADD CONSTRAINT uc_section_name UNIQUE (name);

ALTER TABLE choice
    ADD CONSTRAINT FK_CHOICE_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE exam_question
    ADD CONSTRAINT FK_EXAMQUESTION_ON_EXAM FOREIGN KEY (exam_id) REFERENCES exam (id);

ALTER TABLE exam_question
    ADD CONSTRAINT FK_EXAMQUESTION_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE exam
    ADD CONSTRAINT FK_EXAM_ON_LEVEL FOREIGN KEY (level_id) REFERENCES level (id);

ALTER TABLE member_answer
    ADD CONSTRAINT FK_MEMBERANSWER_ON_ATTEMPT FOREIGN KEY (attempt_id) REFERENCES test_attempt (id);

ALTER TABLE member_answer
    ADD CONSTRAINT FK_MEMBERANSWER_ON_QUESTION FOREIGN KEY (question_id) REFERENCES question (id);

ALTER TABLE member_answer
    ADD CONSTRAINT FK_MEMBERANSWER_ON_SELECTED_CHOICE FOREIGN KEY (selected_choice_id) REFERENCES choice (id);

ALTER TABLE question_category
    ADD CONSTRAINT FK_QUESTIONCATEGORY_ON_SECTION FOREIGN KEY (section_id) REFERENCES section (id);

ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES question_category (id);

ALTER TABLE question
    ADD CONSTRAINT FK_QUESTION_ON_LEVEL FOREIGN KEY (level_id) REFERENCES level (id);

ALTER TABLE test_attempt
    ADD CONSTRAINT FK_TESTATTEMPT_ON_EXAM FOREIGN KEY (exam_id) REFERENCES exam (id);

ALTER TABLE test_attempt
    ADD CONSTRAINT FK_TESTATTEMPT_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);