CREATE TABLE member_grade
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    icon_url    VARCHAR(255),
    grade_order INTEGER                                 NOT NULL,
    CONSTRAINT pk_membergrade PRIMARY KEY (id)
);

CREATE TABLE member_title
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id   BIGINT,
    title_id    BIGINT,
    acquired_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_membertitle PRIMARY KEY (id)
);

CREATE TABLE title
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    icon_url    VARCHAR(255),
    CONSTRAINT pk_title PRIMARY KEY (id)
);

ALTER TABLE member
    ADD experience BIGINT;

ALTER TABLE member
    ADD grade_id BIGINT;

ALTER TABLE member
    ADD level INTEGER;

ALTER TABLE member
    ALTER COLUMN experience SET NOT NULL;

ALTER TABLE member
    ALTER COLUMN level SET NOT NULL;

ALTER TABLE member_grade
    ADD CONSTRAINT uc_membergrade_name UNIQUE (name);

ALTER TABLE title
    ADD CONSTRAINT uc_title_name UNIQUE (name);

ALTER TABLE member_title
    ADD CONSTRAINT FK_MEMBERTITLE_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (id);

ALTER TABLE member_title
    ADD CONSTRAINT FK_MEMBERTITLE_ON_TITLE FOREIGN KEY (title_id) REFERENCES title (id);

ALTER TABLE member
    ADD CONSTRAINT FK_MEMBER_ON_GRADE FOREIGN KEY (grade_id) REFERENCES member_grade (id);