ALTER TABLE word_kanjis
    DROP CONSTRAINT fk_workan_on_kanji;

ALTER TABLE word_kanjis
    DROP CONSTRAINT fk_workan_on_word;

CREATE TABLE word_kanji
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    word_id  BIGINT,
    kanji_id BIGINT,
    CONSTRAINT pk_word_kanji PRIMARY KEY (id)
);

ALTER TABLE word
    ADD deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE word_kanji
    ADD CONSTRAINT FK_WORD_KANJI_ON_KANJI FOREIGN KEY (kanji_id) REFERENCES kanji (id);

ALTER TABLE word_kanji
    ADD CONSTRAINT FK_WORD_KANJI_ON_WORD FOREIGN KEY (word_id) REFERENCES word (id);

DROP TABLE word_kanjis CASCADE;